# Generated by Django 6.0.5 on 2026-05-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('detections', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
