# Generated by Django 6.0.5 on 2026-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='scanned_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='total',
            new_name='total_engines',
        ),
        migrations.AddField(
            model_name='scanlog',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='saved_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='status',
            field=models.CharField(choices=[('clean', '✅ 안전'), ('malicious', '🚨 악성'), ('suspicious', '⚠️ 의심'), ('unknown', '❓ 미등록')], max_length=20),
        ),
    ]
