# Generated by Django 6.0.5 on 2026-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanlog_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='entropy',
            field=models.FloatField(blank=True, help_text='0~8, 높을수록 암호화/난독화 의심', null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='file_extension',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='file_size',
            field=models.IntegerField(default=0, help_text='바이트 단위'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='0~100, 사전 예측 위험도', null=True),
        ),
    ]
